name: Container build (Shiny)

on:
  push:
    paths:
      - 'containers/shiny/Dockerfile'
      - 'containers/shiny/environment.yml'

jobs:
  push_to_registry:
    name: Push to quay.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to quay.io
        env:
          QUAY_USER: ${{ secrets.REGISTRY_USER }}
          QUAY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: podman login -u ${QUAY_USER} -p ${QUAY_PASSWORD} quay.io

      - name: Build container
        run: podman build --tag beckerlab/aradeepopsis-shiny containers/shiny

      - name: Push container
        run: podman push beckerlab/aradeepopsis-shiny docker://quay.io/beckerlab/aradeepopsis-shiny:${GITHUB_REF##*/}