name: Integration test
on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches-ignore:
      - master

jobs:
  CI:
    env:
      PROFILE: ${{ matrix.engine }}
      NXF_VER: ${{ matrix.nxf_ver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        engine: ["docker", "podman", "charliecloud", "conda"]
        nxf_ver: ["21.04.0",""]
        os: ["ubuntu-latest", "macos-latest"]
        exclude:
          - os: "macos-latest"
            engine: "docker"
          - os: "macos-latest"
            engine: "podman"
          - os: "macos-latest"
            engine: "charliecloud"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        if: ${{ matrix.engine == 'charliecloud' }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Charliecloud
        if: ${{ matrix.engine == 'charliecloud' }}
        run: |
          python -m pip install requests
          wget -qO- https://github.com/hpc/charliecloud/releases/download/v0.25/charliecloud-0.25.tar.gz | tar -xvz
          cd charliecloud-0.25
          ./configure
          make
          sudo make install

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run ARADEEPOPSIS on ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          nextflow run ${GITHUB_WORKSPACE} --save_rosette --save_histogram --save_hull --summary_diagnostics --shiny false -profile test,${PROFILE}

      - name: Run ARADEEPOPSIS on macOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sudo chown -R ${UID} ${CONDA}
          nextflow run ${GITHUB_WORKSPACE} --save_rosette --save_histogram --save_hull --summary_diagnostics --shiny false -profile test,conda

      - name: Upload segmentation results
        uses: actions/upload-artifact@v2
        with:
          name: summary_diagnostics ${{ matrix.os }} ${{ matrix.engine }} ${{ matrix.nxf_ver }}
          path: results/diagnostics/summary

      - name: Upload Nextflow report
        uses: actions/upload-artifact@v2
        with:
          name: execution_report ${{ matrix.os }} ${{ matrix.engine }} ${{ matrix.nxf_ver }}
          path: results/www/execution_report.html